// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr_ekRdDWrD3syDpAkzvA_xFJbS8FfTfY',
    appId: '1:958219284269:web:d3736dde1959db2b79eda4',
    messagingSenderId: '958219284269',
    projectId: 'renasport-90390',
    authDomain: 'renasport-90390.firebaseapp.com',
    storageBucket: 'renasport-90390.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1mQzX-06t9sC0R3aIf4s7NsZG6yEXqf4',
    appId: '1:958219284269:android:bbfa7a0ffd66410479eda4',
    messagingSenderId: '958219284269',
    projectId: 'renasport-90390',
    storageBucket: 'renasport-90390.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYDugXqL8552hPU9MMs9lD_0ddGp2YtP4',
    appId: '1:958219284269:ios:920d0f7c56da211f79eda4',
    messagingSenderId: '958219284269',
    projectId: 'renasport-90390',
    storageBucket: 'renasport-90390.firebasestorage.app',
    iosBundleId: 'fr.test.testflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYDugXqL8552hPU9MMs9lD_0ddGp2YtP4',
    appId: '1:958219284269:ios:920d0f7c56da211f79eda4',
    messagingSenderId: '958219284269',
    projectId: 'renasport-90390',
    storageBucket: 'renasport-90390.firebasestorage.app',
    iosBundleId: 'fr.test.testflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr_ekRdDWrD3syDpAkzvA_xFJbS8FfTfY',
    appId: '1:958219284269:web:a09d8af7438d41c479eda4',
    messagingSenderId: '958219284269',
    projectId: 'renasport-90390',
    authDomain: 'renasport-90390.firebaseapp.com',
    storageBucket: 'renasport-90390.firebasestorage.app',
  );
}
